version: '3.8'

services:
  # api:
  #   build: .
  #   container_name: node-api
  #   ports:
  #     - ${HOST_API_PORT}:${PORT}
  #   volumes:
  #     - ${HOST_LOG_PATH}:/usr/app/log
  #     - ./src:/usr/app/src
  #   depends_on:
  #     - db
  #   restart: always
  #   networks:
  #     - skynet
  db:
    build: ./database/
    container_name: ${DB_HOST_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${HOST_PERSISTS_PGDATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: -p ${DB_PORT}
    restart: always
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
